### ISSUE TITLE
Netstandard 2 support

### ISSUE THREAD

**Issue by michaelonz** [galadril/Xam.Shell.Badge#25]
This doesnt appear to work on netstandard 2 projects 

You get the following errors adding it - NOTE I changed project name to XXXX for privacy reasons

Restoring packages for D:\Share\repomike\XXXX\XXXX\XXXX.csproj...
Restoring packages for D:\Share\repomike\XXXX\XXXX.iOS\XXXX.iOS.csproj...
Restoring packages for D:\Share\repomike\XXXX\XXXX.Android\XXXX.Android.csproj...
NU1202: Package Xam.Shell.Badge 1.0.13 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xam.Shell.Badge 1.0.13 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)
  - xamarinios (Xamarin.iOS,Version=v0.0)
Package restore failed. Rolling back package changes for 'XXXX'.
Time Elapsed: 00:00:01.1595138
========== Finished ==========

**Comment by SnowPowerCore** [comment]
Hello, @michaelonz, is it possible for you to update your private shared .NET Standard project to `netstandard2.1` by editing its `.csproj` file?

**Comment by michaelonz** [comment]
I have converted it to 2.1 but am getting a null reference exception (error pasted below):

Interesting part is the error is clearly in the badge - but I have NOT put any badges on tabs at this point?

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]   at Xam.Shell.Badge.Droid.Renderers.BadgeShellItemRenderer.ApplyBadge (System.Int32 itemId, System.String badgeText, Xamarin.Forms.Color badgeBg, Xamarin.Forms.Color textColor) [0x00031] in <f4af92293040425b817ee80f5fffa8dd>:0 
[mono-rt]   at Xam.Shell.Badge.Droid.Renderers.BadgeShellItemRenderer.UpdateBadge (Xamarin.Forms.ShellSection item) [0x00027] in <f4af92293040425b817ee80f5fffa8dd>:0 
[mono-rt]   at Xam.Shell.Badge.Droid.Renderers.BadgeShellItemRenderer.InitBadges () [0x00016] in <f4af92293040425b817ee80f5fffa8dd>:0 
[mono-rt]   at Xamarin.Forms.Device+<>c__DisplayClass43_0.<InvokeOnMainThreadAsync>g__wrapAction|0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Device.cs:130 
[mono-rt]   at Xamarin.Forms.Device+<>c__DisplayClass42_0`1[T].<InvokeOnMainThreadAsync>b__0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Device.cs:116 
[mono-rt] --- End of stack trace from previous location where exception was thrown ---
[mono-rt] 
[mono-rt]   at AsyncAwaitBestPractices.SafeFireAndForgetExtensions.HandleSafeFireAndForget[TException] (System.Threading.Tasks.Task task, System.Boolean continueOnCapturedContext, System.Action`1[T] onException) [0x0006f] in <8039d31f240b405abc8435fcdbcacf54>:0 
[mono-rt]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.26(intptr,intptr)
[mono-rt]   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.26(intptr,intptr)
[HostConnection] HostConnection::get() New Host Connection established 0xdb396900, tid 7923
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2

**Comment by SnowPowerCore** [comment]
Thank you for this stacktrace.

**Comment by SnowPowerCore** [comment]
@michaelonz, can i ask you, if you could provide the name of your emulator, device name and OS you were trying to test this library on...

**Comment by michaelonz** [comment]
Hi - I will run the sample on my emulator and try and work out the differences and let you what caused it - I will report back here.

**Comment by michaelonz** [comment]
Hi SnowPowerCore,
   Using your sample i have worked out the trigger for the exception:

this is your sample shell tab layout:

 <TabBar x:Name="tabBar">
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test1"            
             badge:Badge.BackgroundColor="{Binding Badge1Color}"
             badge:Badge.Text="{Binding Badge1Text}">
            <ShellContent  ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test2"
             badge:Badge.Text="0"
             badge:Badge.BackgroundColor="Purple">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab  Icon="baseline_accessibility_white_24"
             Title="Test3"
             badge:Badge.Text="">
            <ShellContent  ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test4"
             badge:Badge.BackgroundColor="Green"
             badge:Badge.Text="200">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
    </TabBar>

That works - however if you add an IsVisible to a content template (or tab) then it has a null reference exception - e.g:

 <TabBar x:Name="tabBar">
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test1"            
             badge:Badge.BackgroundColor="{Binding Badge1Color}"
             badge:Badge.Text="{Binding Badge1Text}">
            <ShellContent  IsVisible="False" ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test2"
             badge:Badge.Text="0"
             badge:Badge.BackgroundColor="Purple">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab  Icon="baseline_accessibility_white_24"
             Title="Test3"
             badge:Badge.Text="">
            <ShellContent  ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test4"
             badge:Badge.BackgroundColor="Green"
             badge:Badge.Text="200">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
    </TabBar>


NOTE: The first tab has:

<ShellContent  IsVisible="False" ContentTemplate="{DataTemplate local:MainPage}" />


Its the IsVisible="False" that is triggering the error - i think the badge code needs to check if the tab is visible or not to avoid the error maybe?

Let me know if you want me to test anything else?

**Comment by SnowPowerCore** [comment]
Thank you, @michaelonz, i was able to fix it by the information received from you. PR #26 was published.

**Comment by michaelonz** [comment]
Hi SnowPowerCore, 
    Im not sure how to test this from the PR?  Are you able to roll it onto a nuget?

**Comment by galadril** [comment]
Package is now available on Nuget on v1.0.15

**Comment by SnowPowerCore** [comment]
Thank you, @galadril :)

**Comment by SnowPowerCore** [comment]
Hello, @michaelonz, can you confirm the problem is solved?

**Comment by michaelonz** [comment]
Hi,
  It still won’t run and I just have to resolve an issue in another oorojwct then I will take another look - there
Must be a 2nd issue I suspect…. I will try and narrow it down again by taking my code over to the sample a piece at a time…. I will try and get it done this weekend - I will report back here.


Regards

Mike

**Comment by SnowPowerCore** [comment]
@michaelonz, no problem, thank you for reporting

**Comment by SnowPowerCore** [comment]
Hello, @michaelonz, do you have an update on the state of this issue?

**Comment by michaelonz** [comment]
Hi @SnowPowerCore,
   Today I downloaded the sample again (v 1.0.17) and modified the shell to have

 ```
  <Tab 
            IsVisible="False"
             Title="Test1"
             badge:Badge.BackgroundColor="{Binding Badge1Color}"
             badge:Badge.Text="{Binding Badge1Text}">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
```
When you run the sample it still blows up with:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at Xam.Shell.Badge.iOS.Renderers.BadgeShellItemRenderer.ApplyBadge (System.Int32 index, System.String text, Xamarin.Forms.Color bg, Xamarin.Forms.Color textColor) [0x00067] in <0200569c61a546d69290f100e7af4729>:0
  at Xam.Shell.Badge.iOS.Renderers.BadgeShellItemRenderer.UpdateBadge (Xamarin.Forms.ShellSection item) [0x00027] in <0200569c61a546d69290f100e7af4729>:0
  at Xam.Shell.Badge.iOS.Renderers.BadgeShellItemRenderer.InitBadges () [0x00016] in <0200569c61a546d69290f100e7af4729>:0
  at Xamarin.Forms.Device+<>c__DisplayClass43_0.<InvokeOnMainThreadAsync>g__wrapAction|0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Device.cs:130
  at Xamarin.Forms.Device+<>c__DisplayClass42_0`1[T].<InvokeOnMainThreadAsync>b__0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Device.cs:116
  at AsyncAwaitBestPractices.SafeFireAndForgetExtensions.HandleSafeFireAndForget[TException] (System.Threading.Tasks.Task task, System.Boolean continueOnCapturedContext, System.Action`1[T] onException) [0x0006f] in <8039d31f240b405abc8435fcdbcacf54>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:178
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:73
  at Xam.Shell.Badge.Sample.iOS.Application.Main (System.String[] args) [0x00001] in /Users/michaelo/Downloads/Xam.Shell.Badge-master/sample/Xam.Shell.Badge.Sample/Xam.Shell.Badge.Sample.iOS/Main.cs:27


This is still being caused by the IsVisible="False" 

I thought a new Nuget had been published (1.0.17) with the fix - or am I doing something wrong?

My test was literally the sample app with the code change above and running on the iOS simulator for iPhone 13 IOS15.2

Any suggestions appreciated.

**Comment by SnowPowerCore** [comment]
Hello, @michaelonz, thank you for reporting. With the stacktrace you specified before your new message it was obvious that it was an Android issue. You haven't mentioned iOS before this new comment.
#31 PR resolves this for iOS. Android should be resolved since Nuget package v1.0.15 and #26.

**Comment by michaelonz** [comment]
Hi Guys,  
    I have tested the original issue on android and with v 1.17 when you set Visible=False it works now as expected so that is good - I will test ios later today hopefully.

I am also using FontImageSource  (eg using fontawesome for the image) on my existing tabs -eg

        <Tab  
             Title="Test1"
             badge:Badge.BackgroundColor="{Binding Badge1Color}"
             badge:Badge.Text="{Binding Badge1Text}">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}">
                <d:ShellContent.Icon>
                    <FontImageSource Color="Black" FontFamily="{DynamicResource IconFontFamily}" Glyph="{StaticResource  IconAlerts}"/>
                </d:ShellContent.Icon>
            </ShellContent>
        </Tab>

This icon does not draw when its from FontImageSource - (using Icon= does work) - it would be great if that worked also as (I think it is fairly common use case these days).

I will test ios and let you know how that goes as well - thanks for the support

**Comment by michaelonz** [comment]
Hi Guys,
  Tested #31 on IOS today and the IsVisible=False is now working correctly on IOS - so I think that we can close off the initial issue.

There are 2 things I have noticed while testing this :

1) As per above FontImageSource isn't supported but it would be great if that worked as its a common use case now
2) I also noted that when you click the 'Change Colour First Badge' buttons in the sample - that works fine on Android but it does not change on IOS (at least that was the case with PR #31)

Do you think you will add FontImageSource support - I would be able to test that for you if you do it....if you are adding it soon then I will leave my code and use that as the test....otherwise I will revisit using fontawesome and go back to Icon= ....

Thanks for the support.

**Comment by SnowPowerCore** [comment]
Hello, @michaelonz. I've followed this [instruction](https://www.damirscorner.com/blog/posts/20201113-UsingFontAwesomeInXamarinForms.html) and have successfully replaced one of the `Tab` item's icon with `FontImageSource`.
```XAML
<Tab Title="Test1"
    badge:Badge.BackgroundColor="{Binding Badge1Color}"
    badge:Badge.Text="{Binding Badge1Text}">
        <Tab.Icon>
            <FontImageSource FontFamily="FontAwesome6Regular"
                Color="Black" Glyph="&#xf164;"/>
        </Tab.Icon>
    <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
</Tab>
```

![image](https://user-images.githubusercontent.com/35460261/154868905-c73a9dee-3249-444b-baab-ad556edf4409.png)
_(Thumbs up icon comes from FontAwesome)_.

Also, i'm unable to reproduce the problem with the button you mentioned: it switches the color in every iOS simulator i typically use for testing. If you could share some details on that, i'd be happy to follow and try to help.

**Comment by michaelonz** [comment]
Hi Guys,
   I retested and it was a typo - fontawesome does work (at least it did on android - havent tested ios yet).
So I guess this means we are all done. Can we roll fix #31  into a nuget so we can use nuget to add the fix to the app (I guess nuget version 18 as original test was on 17).

Thanks for the great support

**Comment by SnowPowerCore** [comment]
@galadril, we need your help on this.

**Comment by galadril** [comment]
I've merged it, but im not able to build a nuget at the moment.
Ill probably have time within 12 hours!

**Comment by SnowPowerCore** [comment]
@galadril, thank you

**Comment by michaelonz** [comment]
Hi @SnowPowerCore  and @galadril ,

 I moved this into my app and actually found that under a specific circumstance it still does have an issue and i have replicated it below in the sample.

If you use the sample and change the tabs to the following:

You would expect to see tab1,tab3,tab4 (tab2 should be invisible)

`<TabBar x:Name="tabBar">
        <Tab  IsVisible="True"
             Title="Test1"
             badge:Badge.BackgroundColor="{Binding Badge1Color}"
             badge:Badge.Text="1">
            <Tab.Icon>
                <FontImageSource FontFamily="{StaticResource IconFontFamily}"
                Color="Black" Glyph="{StaticResource  IconBell}"/>
            </Tab.Icon>

            <ShellContent ContentTemplate="{DataTemplate local:MainPage}">
               
            </ShellContent>
        </Tab>
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test2"
             IsVisible="False"
             badge:Badge.Text="2"
             badge:Badge.BackgroundColor="Purple">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test3"
             badge:Badge.Text="3">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
        <Tab Icon="baseline_accessibility_white_24"
             Title="Test4"
             badge:Badge.BackgroundColor="Green"
             badge:Badge.Text="4">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
        </Tab>
    </TabBar>` 

But what you get is 

Tab1, Tab3 and Tab4 (so far this is right) - however the badge text that are shown are for badge tab1 tab2 and tab3   (should be tab1, tab3, tab4) ...so we are getting the wrong badge text.

When the tab is IsVisible=False then the badge needs to be skipped also.



Below is an image showing the output that is incorrect - (NOTE In the xaml i change the title and badge text to match to make it obvious)

![image](https://user-images.githubusercontent.com/20587873/154926599-26cd94e0-57e9-4a5b-bc02-30ff808fe88f.png)

Happy to retest once its resolved.... just let me know when to test

**Comment by galadril** [comment]
Created new nuget package: `v1.0.18`

**Comment by michaelonz** [comment]
thanks @galadril  - can the issue above be resolved?  (the one where it is showing the badge text on the wrong tab) - its 2 comments back from here - basically take the tab code i showed and it replicates in the sample

**Comment by michaelonz** [comment]
hi @galadril - any change of investigating the issue above (badge text shows on wrong tab when you set IsVisible = false on preceeding tabs - i have supplied sample tab code above to replicate. (NOTE I was testing on android - have not tried that on IOS as yet)

**Comment by SnowPowerCore** [comment]
@michaelonz, i'm sorry, fix will be delayed until the weekends.

**Comment by michaelonz** [comment]
Hi @SnowPowerCore  - I have tested on IOS now and it has the same issue as well where the badge appears on the wrong tab when you set a preceeding one to IsVisible = false (see my sample tabs above to replicate posted feb21 20:29pm).  My guess is its using the tabindex and not checking if IsVisible = false as it works through..... let me know when you would like it tested.

**Comment by michaelonz** [comment]
@galadril - is there any chance of getting the last issue above resolved? - its basically unusable right now when you show/hide a tab in the shell because the badge moves to the wrong tab.

**Comment by SnowPowerCore** [comment]
@michaelonz, hello, my deepest apologizes. I will try to resolve this either today, or tomorrow.

**Comment by michaelonz** [comment]
Thanks @SnowPowerCore

**Comment by michaelonz** [comment]
@SnowPowerCore  any luck?

**Comment by SnowPowerCore** [comment]
@michaelonz, hello, yes, i'm trying to fix all opened issue and compile them into one PR. Meanwhile, please, follow the changes available in the new branch `[bugfix/Fixing-Recent-Issues-#23-#25-#32](https://github.com/galadril/Xam.Shell.Badge/tree/bugfix/Fixing-Recent-Issues-%2323-%2325-%2332)`.

**Comment by michaelonz** [comment]
Hi @SnowPowerCore - sounds like good progress. Would be good if flyoutit could also support badge as well.

**Comment by michaelonz** [comment]
Hi Guys, 
  I downloaded this and tested it and initial tests look good (NOTE: I had to add some references to projects to get the src to compile) but once it compiled it worked as expected.  I think this can be rolled into a Nuget now - thanks.

**Comment by michaelonz** [comment]
Hi @galadril and @SnowPowerCore - I have tested this on both android and iOS now and it works well - the text containment issue and the text on the wrong badge - both issues can be closed on both platforms.  Thanks for the effort guys. Adding fly out badges would be a good improvement but that’s not a show stopper for me (just a nice to have that would mean this plugin covers most badge scenarios with shell - which is very lacking in other plugins - shell is almost like the ugly step sister when it comes to add ons :) )

**Comment by SnowPowerCore** [comment]
@michaelonz, thanks for the review and for the tip. After we merge the current PR, i'll look into possible ways of adding badges to Shell flyout menus.

**Comment by SnowPowerCore** [comment]
@michaelonz, i'm closing this issue as it has become pretty large and you've reported that everything works fine when you pulled those changes into the local environment. If you find any other problem, please, feel free to create new issue.
